name: "🐛 Bug Report"
description: Report a reproducible problem within Geek Protocol
labels:
  - bug
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve Geek Protocol! Please provide as much detail as possible so we can reproduce the issue quickly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Brief description of the problem
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the exact steps, commands, or actions to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Observe error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Screenshots
      description: Include logs, stack traces, or screenshots when possible.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Impacted Area
      options:
        - Web (Next.js)
        - API (Fastify)
        - Rewards Worker
        - Infrastructure / DevOps
        - Documentation
        - Other / Unsure
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: OS, browser, Node.js version, etc.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other context, links, or references.
    validations:
      required: false
