name: "✨ Feature Request"
description: Suggest a new idea or improvement for Geek Protocol
labels:
  - enhancement
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        Have an idea that would make Geek Protocol better? Tell us about it!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or improved?
      placeholder: Concise description of the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: What problem does this solve? What value does it create?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe how the feature should work. Include mockups or references if you have them.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other approaches?
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area of Impact
      options:
        - Web (Next.js)
        - API (Fastify)
        - Rewards Worker
        - Infrastructure / DevOps
        - Documentation / Content
        - Ecosystem / Partnerships
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, metrics, or anything else we should know.
    validations:
      required: false
